// Generated by jextract

package com.icuxika.taskbar_manager.jextract.win32;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.util.Arrays;
import java.util.stream.Collectors;

import static java.lang.foreign.ValueLayout.*;

public class ffm_h {

    ffm_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
        String traceArgs = Arrays.stream(args)
                .map(Object::toString)
                .collect(Collectors.joining(", "));
        System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
                .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("User32"), LIBRARY_ARENA)
            .or(SymbolLookup.libraryLookup(System.mapLibraryName("Kernel32"), LIBRARY_ARENA))
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfInt C_LONG = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfDouble C_LONG_DOUBLE = ValueLayout.JAVA_DOUBLE;
    private static final int GW_OWNER = (int) 4L;

    /**
     * {@snippet lang = c:
     * #define GW_OWNER 4
     *}
     */
    public static int GW_OWNER() {
        return GW_OWNER;
    }

    /**
     * {@snippet lang = c:
     * typedef unsigned long DWORD
     *}
     */
    public static final OfInt DWORD = ffm_h.C_LONG;
    /**
     * {@snippet lang = c:
     * typedef int BOOL
     *}
     */
    public static final OfInt BOOL = ffm_h.C_INT;
    /**
     * {@snippet lang = c:
     * typedef DWORD *LPDWORD
     *}
     */
    public static final AddressLayout LPDWORD = ffm_h.C_POINTER;
    /**
     * {@snippet lang = c:
     * typedef unsigned int UINT
     *}
     */
    public static final OfInt UINT = ffm_h.C_INT;
    /**
     * {@snippet lang = c:
     * typedef WCHAR *LPWSTR
     *}
     */
    public static final AddressLayout LPWSTR = ffm_h.C_POINTER;
    /**
     * {@snippet lang = c:
     * typedef void *HANDLE
     *}
     */
    public static final AddressLayout HANDLE = ffm_h.C_POINTER;
    /**
     * {@snippet lang = c:
     * typedef LONG_PTR LPARAM
     *}
     */
    public static final OfLong LPARAM = ffm_h.C_LONG_LONG;
    /**
     * {@snippet lang = c:
     * typedef HINSTANCE HMODULE
     *}
     */
    public static final AddressLayout HMODULE = ffm_h.C_POINTER;
    /**
     * {@snippet lang = c:
     * typedef struct HWND__ {
     *     int unused;
     * } *HWND
     *}
     */
    public static final AddressLayout HWND = ffm_h.C_POINTER;

    private static class CloseHandle {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("CloseHandle");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * BOOL CloseHandle(HANDLE hObject)
     *}
     */
    public static FunctionDescriptor CloseHandle$descriptor() {
        return CloseHandle.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * BOOL CloseHandle(HANDLE hObject)
     *}
     */
    public static MethodHandle CloseHandle$handle() {
        return CloseHandle.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * BOOL CloseHandle(HANDLE hObject)
     *}
     */
    public static MemorySegment CloseHandle$address() {
        return CloseHandle.ADDR;
    }

    /**
     * {@snippet lang = c:
     * BOOL CloseHandle(HANDLE hObject)
     *}
     */
    public static int CloseHandle(MemorySegment hObject) {
        var mh$ = CloseHandle.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("CloseHandle", hObject);
            }
            return (int) mh$.invokeExact(hObject);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class OpenProcess {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_POINTER,
                ffm_h.C_LONG,
                ffm_h.C_INT,
                ffm_h.C_LONG
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("OpenProcess");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * HANDLE OpenProcess(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId)
     *}
     */
    public static FunctionDescriptor OpenProcess$descriptor() {
        return OpenProcess.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * HANDLE OpenProcess(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId)
     *}
     */
    public static MethodHandle OpenProcess$handle() {
        return OpenProcess.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * HANDLE OpenProcess(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId)
     *}
     */
    public static MemorySegment OpenProcess$address() {
        return OpenProcess.ADDR;
    }

    /**
     * {@snippet lang = c:
     * HANDLE OpenProcess(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId)
     *}
     */
    public static MemorySegment OpenProcess(int dwDesiredAccess, int bInheritHandle, int dwProcessId) {
        var mh$ = OpenProcess.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("OpenProcess", dwDesiredAccess, bInheritHandle, dwProcessId);
            }
            return (MemorySegment) mh$.invokeExact(dwDesiredAccess, bInheritHandle, dwProcessId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ShowWindow {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER,
                ffm_h.C_INT
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("ShowWindow");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * BOOL ShowWindow(HWND hWnd, int nCmdShow)
     *}
     */
    public static FunctionDescriptor ShowWindow$descriptor() {
        return ShowWindow.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * BOOL ShowWindow(HWND hWnd, int nCmdShow)
     *}
     */
    public static MethodHandle ShowWindow$handle() {
        return ShowWindow.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * BOOL ShowWindow(HWND hWnd, int nCmdShow)
     *}
     */
    public static MemorySegment ShowWindow$address() {
        return ShowWindow.ADDR;
    }

    /**
     * {@snippet lang = c:
     * BOOL ShowWindow(HWND hWnd, int nCmdShow)
     *}
     */
    public static int ShowWindow(MemorySegment hWnd, int nCmdShow) {
        var mh$ = ShowWindow.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ShowWindow", hWnd, nCmdShow);
            }
            return (int) mh$.invokeExact(hWnd, nCmdShow);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class IsWindowVisible {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("IsWindowVisible");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * BOOL IsWindowVisible(HWND hWnd)
     *}
     */
    public static FunctionDescriptor IsWindowVisible$descriptor() {
        return IsWindowVisible.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * BOOL IsWindowVisible(HWND hWnd)
     *}
     */
    public static MethodHandle IsWindowVisible$handle() {
        return IsWindowVisible.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * BOOL IsWindowVisible(HWND hWnd)
     *}
     */
    public static MemorySegment IsWindowVisible$address() {
        return IsWindowVisible.ADDR;
    }

    /**
     * {@snippet lang = c:
     * BOOL IsWindowVisible(HWND hWnd)
     *}
     */
    public static int IsWindowVisible(MemorySegment hWnd) {
        var mh$ = IsWindowVisible.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("IsWindowVisible", hWnd);
            }
            return (int) mh$.invokeExact(hWnd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class IsIconic {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("IsIconic");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * BOOL IsIconic(HWND hWnd)
     *}
     */
    public static FunctionDescriptor IsIconic$descriptor() {
        return IsIconic.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * BOOL IsIconic(HWND hWnd)
     *}
     */
    public static MethodHandle IsIconic$handle() {
        return IsIconic.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * BOOL IsIconic(HWND hWnd)
     *}
     */
    public static MemorySegment IsIconic$address() {
        return IsIconic.ADDR;
    }

    /**
     * {@snippet lang = c:
     * BOOL IsIconic(HWND hWnd)
     *}
     */
    public static int IsIconic(MemorySegment hWnd) {
        var mh$ = IsIconic.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("IsIconic", hWnd);
            }
            return (int) mh$.invokeExact(hWnd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class SetForegroundWindow {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("SetForegroundWindow");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * BOOL SetForegroundWindow(HWND hWnd)
     *}
     */
    public static FunctionDescriptor SetForegroundWindow$descriptor() {
        return SetForegroundWindow.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * BOOL SetForegroundWindow(HWND hWnd)
     *}
     */
    public static MethodHandle SetForegroundWindow$handle() {
        return SetForegroundWindow.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * BOOL SetForegroundWindow(HWND hWnd)
     *}
     */
    public static MemorySegment SetForegroundWindow$address() {
        return SetForegroundWindow.ADDR;
    }

    /**
     * {@snippet lang = c:
     * BOOL SetForegroundWindow(HWND hWnd)
     *}
     */
    public static int SetForegroundWindow(MemorySegment hWnd) {
        var mh$ = SetForegroundWindow.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("SetForegroundWindow", hWnd);
            }
            return (int) mh$.invokeExact(hWnd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetWindowTextW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER,
                ffm_h.C_POINTER,
                ffm_h.C_INT
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("GetWindowTextW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount)
     *}
     */
    public static FunctionDescriptor GetWindowTextW$descriptor() {
        return GetWindowTextW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount)
     *}
     */
    public static MethodHandle GetWindowTextW$handle() {
        return GetWindowTextW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount)
     *}
     */
    public static MemorySegment GetWindowTextW$address() {
        return GetWindowTextW.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount)
     *}
     */
    public static int GetWindowTextW(MemorySegment hWnd, MemorySegment lpString, int nMaxCount) {
        var mh$ = GetWindowTextW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetWindowTextW", hWnd, lpString, nMaxCount);
            }
            return (int) mh$.invokeExact(hWnd, lpString, nMaxCount);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetWindowTextLengthW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("GetWindowTextLengthW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int GetWindowTextLengthW(HWND hWnd)
     *}
     */
    public static FunctionDescriptor GetWindowTextLengthW$descriptor() {
        return GetWindowTextLengthW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int GetWindowTextLengthW(HWND hWnd)
     *}
     */
    public static MethodHandle GetWindowTextLengthW$handle() {
        return GetWindowTextLengthW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int GetWindowTextLengthW(HWND hWnd)
     *}
     */
    public static MemorySegment GetWindowTextLengthW$address() {
        return GetWindowTextLengthW.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int GetWindowTextLengthW(HWND hWnd)
     *}
     */
    public static int GetWindowTextLengthW(MemorySegment hWnd) {
        var mh$ = GetWindowTextLengthW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetWindowTextLengthW", hWnd);
            }
            return (int) mh$.invokeExact(hWnd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetWindowLongW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_LONG,
                ffm_h.C_POINTER,
                ffm_h.C_INT
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("GetWindowLongW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * LONG GetWindowLongW(HWND hWnd, int nIndex)
     *}
     */
    public static FunctionDescriptor GetWindowLongW$descriptor() {
        return GetWindowLongW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * LONG GetWindowLongW(HWND hWnd, int nIndex)
     *}
     */
    public static MethodHandle GetWindowLongW$handle() {
        return GetWindowLongW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * LONG GetWindowLongW(HWND hWnd, int nIndex)
     *}
     */
    public static MemorySegment GetWindowLongW$address() {
        return GetWindowLongW.ADDR;
    }

    /**
     * {@snippet lang = c:
     * LONG GetWindowLongW(HWND hWnd, int nIndex)
     *}
     */
    public static int GetWindowLongW(MemorySegment hWnd, int nIndex) {
        var mh$ = GetWindowLongW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetWindowLongW", hWnd, nIndex);
            }
            return (int) mh$.invokeExact(hWnd, nIndex);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetParent {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_POINTER,
                ffm_h.C_POINTER
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("GetParent");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * HWND GetParent(HWND hWnd)
     *}
     */
    public static FunctionDescriptor GetParent$descriptor() {
        return GetParent.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * HWND GetParent(HWND hWnd)
     *}
     */
    public static MethodHandle GetParent$handle() {
        return GetParent.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * HWND GetParent(HWND hWnd)
     *}
     */
    public static MemorySegment GetParent$address() {
        return GetParent.ADDR;
    }

    /**
     * {@snippet lang = c:
     * HWND GetParent(HWND hWnd)
     *}
     */
    public static MemorySegment GetParent(MemorySegment hWnd) {
        var mh$ = GetParent.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetParent", hWnd);
            }
            return (MemorySegment) mh$.invokeExact(hWnd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EnumWindows {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER,
                ffm_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("EnumWindows");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * BOOL EnumWindows(WNDENUMPROC lpEnumFunc, LPARAM lParam)
     *}
     */
    public static FunctionDescriptor EnumWindows$descriptor() {
        return EnumWindows.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * BOOL EnumWindows(WNDENUMPROC lpEnumFunc, LPARAM lParam)
     *}
     */
    public static MethodHandle EnumWindows$handle() {
        return EnumWindows.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * BOOL EnumWindows(WNDENUMPROC lpEnumFunc, LPARAM lParam)
     *}
     */
    public static MemorySegment EnumWindows$address() {
        return EnumWindows.ADDR;
    }

    /**
     * {@snippet lang = c:
     * BOOL EnumWindows(WNDENUMPROC lpEnumFunc, LPARAM lParam)
     *}
     */
    public static int EnumWindows(MemorySegment lpEnumFunc, long lParam) {
        var mh$ = EnumWindows.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EnumWindows", lpEnumFunc, lParam);
            }
            return (int) mh$.invokeExact(lpEnumFunc, lParam);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetClassNameW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_INT,
                ffm_h.C_POINTER,
                ffm_h.C_POINTER,
                ffm_h.C_INT
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("GetClassNameW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * int GetClassNameW(HWND hWnd, LPWSTR lpClassName, int nMaxCount)
     *}
     */
    public static FunctionDescriptor GetClassNameW$descriptor() {
        return GetClassNameW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * int GetClassNameW(HWND hWnd, LPWSTR lpClassName, int nMaxCount)
     *}
     */
    public static MethodHandle GetClassNameW$handle() {
        return GetClassNameW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * int GetClassNameW(HWND hWnd, LPWSTR lpClassName, int nMaxCount)
     *}
     */
    public static MemorySegment GetClassNameW$address() {
        return GetClassNameW.ADDR;
    }

    /**
     * {@snippet lang = c:
     * int GetClassNameW(HWND hWnd, LPWSTR lpClassName, int nMaxCount)
     *}
     */
    public static int GetClassNameW(MemorySegment hWnd, MemorySegment lpClassName, int nMaxCount) {
        var mh$ = GetClassNameW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetClassNameW", hWnd, lpClassName, nMaxCount);
            }
            return (int) mh$.invokeExact(hWnd, lpClassName, nMaxCount);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetWindowThreadProcessId {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_LONG,
                ffm_h.C_POINTER,
                ffm_h.C_POINTER
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("GetWindowThreadProcessId");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * DWORD GetWindowThreadProcessId(HWND hWnd, LPDWORD lpdwProcessId)
     *}
     */
    public static FunctionDescriptor GetWindowThreadProcessId$descriptor() {
        return GetWindowThreadProcessId.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * DWORD GetWindowThreadProcessId(HWND hWnd, LPDWORD lpdwProcessId)
     *}
     */
    public static MethodHandle GetWindowThreadProcessId$handle() {
        return GetWindowThreadProcessId.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * DWORD GetWindowThreadProcessId(HWND hWnd, LPDWORD lpdwProcessId)
     *}
     */
    public static MemorySegment GetWindowThreadProcessId$address() {
        return GetWindowThreadProcessId.ADDR;
    }

    /**
     * {@snippet lang = c:
     * DWORD GetWindowThreadProcessId(HWND hWnd, LPDWORD lpdwProcessId)
     *}
     */
    public static int GetWindowThreadProcessId(MemorySegment hWnd, MemorySegment lpdwProcessId) {
        var mh$ = GetWindowThreadProcessId.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetWindowThreadProcessId", hWnd, lpdwProcessId);
            }
            return (int) mh$.invokeExact(hWnd, lpdwProcessId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetWindow {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                ffm_h.C_POINTER,
                ffm_h.C_POINTER,
                ffm_h.C_INT
        );

        public static final MemorySegment ADDR = ffm_h.findOrThrow("GetWindow");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c:
     * HWND GetWindow(HWND hWnd, UINT uCmd)
     *}
     */
    public static FunctionDescriptor GetWindow$descriptor() {
        return GetWindow.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c:
     * HWND GetWindow(HWND hWnd, UINT uCmd)
     *}
     */
    public static MethodHandle GetWindow$handle() {
        return GetWindow.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c:
     * HWND GetWindow(HWND hWnd, UINT uCmd)
     *}
     */
    public static MemorySegment GetWindow$address() {
        return GetWindow.ADDR;
    }

    /**
     * {@snippet lang = c:
     * HWND GetWindow(HWND hWnd, UINT uCmd)
     *}
     */
    public static MemorySegment GetWindow(MemorySegment hWnd, int uCmd) {
        var mh$ = GetWindow.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetWindow", hWnd, uCmd);
            }
            return (MemorySegment) mh$.invokeExact(hWnd, uCmd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static final int PROCESS_VM_READ = (int) 16L;

    /**
     * {@snippet lang = c:
     * #define PROCESS_VM_READ 16
     *}
     */
    public static int PROCESS_VM_READ() {
        return PROCESS_VM_READ;
    }

    private static final int PROCESS_QUERY_INFORMATION = (int) 1024L;

    /**
     * {@snippet lang = c:
     * #define PROCESS_QUERY_INFORMATION 1024
     *}
     */
    public static int PROCESS_QUERY_INFORMATION() {
        return PROCESS_QUERY_INFORMATION;
    }

    private static final int GWL_EXSTYLE = (int) -20L;

    /**
     * {@snippet lang = c:
     * #define GWL_EXSTYLE -20
     *}
     */
    public static int GWL_EXSTYLE() {
        return GWL_EXSTYLE;
    }

    private static final int WS_EX_TOOLWINDOW = (int) 128L;

    /**
     * {@snippet lang = c:
     * #define WS_EX_TOOLWINDOW 128
     *}
     */
    public static int WS_EX_TOOLWINDOW() {
        return WS_EX_TOOLWINDOW;
    }
}

